// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAs8dFDfEUGOlrx1yOKnpp3M9r8K1-a7gM',
//     appId: '1:703102560347:web:ff5ed001fddd32c7fb777e',
//     messagingSenderId: '703102560347',
//     projectId: 'build-audit-f43c7',
//     authDomain: 'build-audit-f43c7.firebaseapp.com',
//     storageBucket: 'build-audit-f43c7.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBAbNmUe1Phx6WukL0vRkQUZfNRtujqAfI',
//     appId: '1:703102560347:android:22c0c66d82a59972fb777e',
//     messagingSenderId: '703102560347',
//     projectId: 'build-audit-f43c7',
//     storageBucket: 'build-audit-f43c7.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAuZaMKXK5nrKDCICSD9EOLyKIyUTS0UFQ',
//     appId: '1:703102560347:ios:d92945f2d4599c28fb777e',
//     messagingSenderId: '703102560347',
//     projectId: 'build-audit-f43c7',
//     storageBucket: 'build-audit-f43c7.firebasestorage.app',
//     iosBundleId: 'com.example.buildAudit',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAuZaMKXK5nrKDCICSD9EOLyKIyUTS0UFQ',
//     appId: '1:703102560347:ios:d92945f2d4599c28fb777e',
//     messagingSenderId: '703102560347',
//     projectId: 'build-audit-f43c7',
//     storageBucket: 'build-audit-f43c7.firebasestorage.app',
//     iosBundleId: 'com.example.buildAudit',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAs8dFDfEUGOlrx1yOKnpp3M9r8K1-a7gM',
//     appId: '1:703102560347:web:98552638ee2beafdfb777e',
//     messagingSenderId: '703102560347',
//     projectId: 'build-audit-f43c7',
//     authDomain: 'build-audit-f43c7.firebaseapp.com',
//     storageBucket: 'build-audit-f43c7.firebasestorage.app',
//   );
// }
